---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - lukemcewen.com
  resources:
  - discordbots
  - shopifydbs
  - shopifyscrapers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lukemcewen.com
  resources:
  - discordbots/finalizers
  - shopifydbs/finalizers
  - shopifyscrapers/finalizers
  verbs:
  - update
- apiGroups:
  - lukemcewen.com
  resources:
  - discordbots/status
  - shopifydbs/status
  - shopifyscrapers/status
  verbs:
  - get
  - patch
  - update
